name: locally defined cargo-checkmate phases

on: [workflow_call]

jobs:
  run-phase:
    strategy:
      matrix:
        phase: [audit, build, check, clippy, doc, format, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            components: clippy
            override: true
      - uses: baptiste0928/cargo-install@v2
        with:
          crate: cargo-checkmate
      - uses: actions/checkout@v3
      - run: cargo-checkmate run ${{ matrix.phase }}
